### ISSUE TITLE
Using saved HTTP requests, Events or Queries is broken

### ISSUE THREAD

**Issue by austencollins** [serverless/desktop#10]
As of `v0.0.107` I'm unable to use saved HTTP requests, Events, or Queries.  When I click on a saved item, or when I save a new item, the view switches to a stage that does not exist (though in this case, the stage used to exist), and the view is blank.

It could be related to the recent change where stage names and regions were combined into the stage name.  However, it also feels like it could be related to the way this stored data is structured.

<img width="1307" alt="Screen Shot 2021-01-07 at 6 47 21 PM" src="https://user-images.githubusercontent.com/2752551/103968480-c7ea0600-5118-11eb-9d08-3b7ee9db6ec9.png">

**Comment by stevewillard** [comment]
Fixed in `Version 0.0.108`
