### ISSUE TITLE
Sync seems to not work with a new Provider

### ISSUE THREAD

**Issue by austencollins** [serverless/desktop#11]
When I delete a Provider and recreated it via the onboarding flow, then run the sync process, the sync process begins but the status from the sync is always `inactive` meaning it was never started.  This screen then hangs indefinitely.

Please note that I have already created Providers, synced with them, removed everything, and deleted Providers multiple times before this.  It is not the case that my account replicates a new user exactly.

**Comment by stevewillard** [comment]
Fixed in`0.0.110`
