### ISSUE TITLE
Strange UI behavior when removing a Connection

### ISSUE THREAD

**Issue by austencollins** [serverless/desktop#13]
When removing a Connection that contained ~50 Serverless Framework Services, the Services list on the left gradually disappears as expected.  

However, once all Services on the left are gone, the removing process continues and single Services randomly show up in the left column for about 2 seconds, then disappear again.  This happened for about 15 Services.

List is gone...
<img width="919" alt="Screen Shot 2021-01-27 at 10 53 50 PM" src="https://user-images.githubusercontent.com/2752551/106101637-027d0800-60f3-11eb-89fe-c1a1ebadaa19.png">

Suddenly individual Services show up again...
<img width="871" alt="Screen Shot 2021-01-27 at 10 53 53 PM" src="https://user-images.githubusercontent.com/2752551/106101646-0577f880-60f3-11eb-94de-18fab27d093c.png">

**Comment by stevewillard** [comment]
That sidebar is polling `listInstances` and grouping them together by `instanceName` to form the service. I wonder if the instance goes from a terminal (not returned state) to some state that is part of `listInstances`.

Maybe a reasonable fix is to filter on the frontend, and only show instances that are `active`. I think there is still a backlog issue for allowing this filtering as part of the API.

**Comment by stevewillard** [comment]
I changed the behavior of the sidebar so that only instances in the following states will appear:
```javascript
['deploying', 'active', 'removing']
```

I'll do some more testing, but I believe this should be fixed in the next version.
