### ISSUE TITLE
Sync errors not being shown to user

### ISSUE THREAD

**Issue by austencollins** [serverless/desktop#16]
When opening a view, and the sync process fails, no error is shown to the user.  Instead, the view is simply blank.

Here is an example where a resource was not found because it was deleted manually, even though it is listed in a CloudFormation stack.

<img width="1029" alt="Screen Shot 2021-02-09 at 12 07 45 PM" src="https://user-images.githubusercontent.com/2752551/107421919-6cbc8200-6acf-11eb-8f77-4f365c48b181.png">

**Comment by stevewillard** [comment]
If a resource has been deleted manually, do we fail the whole sync process, or can we skip over the missing resource?

My preference would to be skip over what's missing, but provide an error array of resources that failed to sync. cc @astuyve

**Comment by astuyve** [comment]
That seems like appropriate acceptance criteria to me! I can start looking into that!

**Comment by astuyve** [comment]
@ac360 I'm unclear on the path by which Traditional component instances are upgraded.

Let's say hypothetically I make this change, likely around this area: https://github.com/serverlessinc/platform/blob/master/sp-connect/code/traditional/src/functions/sync.js#L59-L83
Then I publish a new version of the traditional component.

How do the existing instances get updated? Do they just stay dormant until we call `sync`, and then get re-incarnated with the latest version? Is the expectation that all Traditional component instances will be at the same version at the same time?

**Comment by austencollins** [comment]
@astuyve Correct.  Right now, the Desktop is set to call the LATEST version of the Traditional Component.  This is the default behavior when you do not include a Component version in the `sdk.run()` request.  As soon as you make the change and publish a new version, all Desktop users will use this.  We thought this was best at this innovation phase and considering the Desktop update experience is super smooth.  Later, we may want to investigate the version pinning functionality of Components.
