### ISSUE TITLE
Missing Connection Provider breaks Desktop

### ISSUE THREAD

**Issue by austencollins** [serverless/desktop#17]
In the Serverless Dashboard, I deleted the Provider used by a Connection within Serverless Desktop.  Now, I'm unable to fix my Connection, and all of the Services using that Provider/Connection are broken.

<img width="432" alt="Screen Shot 2021-02-15 at 6 15 51 AM" src="https://user-images.githubusercontent.com/2752551/107951238-437b7600-6f55-11eb-89f3-62de300b55ba.png">

<img width="437" alt="Screen Shot 2021-02-15 at 6 16 04 AM" src="https://user-images.githubusercontent.com/2752551/107951256-49715700-6f55-11eb-805e-4b496c089607.png">

Being able to edit an existing Connection and add a new Provider to it will resolve this problem.  Until then, Desktop is permanently broken for users who experience this.

**Comment by stevewillard** [comment]
That's true, but can't you remove and connection and create a new one to get out of this state?

**Comment by austencollins** [comment]
I do not see any ability ATM to remove a Connection.  The "X" tries to unsync first, then crashes.

**Comment by stevewillard** [comment]
Ah, I see. Ok, I can at least prevent that from crashing. We can also revisit hiding the Desktop providers in the dashboard, to better prevent this from happening.

**Comment by stevewillard** [comment]
Version `0.0.131` has a change which removes the connection, if sync fails. The Desktop Providers are now no longer visible in the web dashboard to prevent this from happening.
