### ISSUE TITLE
Sidebar not visible when app is loaded

### ISSUE THREAD

**Issue by austencollins** [serverless/desktop#22]
On a 13" macbook, when installing and starting the Desktop app for the first time, the sidebar showing apps is not visible despite the app taking up most of the desktop space.  There is also no button to toggle the sidebar.  This makes it seem as if there is no functionality, especially for new users.

<img width="1429" alt="Screen Shot 2021-03-08 at 7 18 44 AM" src="https://user-images.githubusercontent.com/2752551/110333183-85d92580-7fde-11eb-91af-17601b3a263c.png">

**Comment by stevewillard** [comment]
The sidebar auto-hiding has been removed in `0.0.163`. You can still toggle it open and closed with the sidebar icon.
