### ISSUE TITLE
Collaborators are forced to onboard via Desktop when Org is already onboarded

### ISSUE THREAD

**Issue by austencollins** [serverless/desktop#6]
When switching to an Org that is already onboarded onto Desktop as a collaborator (not the owner), you are redirected to a screen that tries to onboard their org by connecting accounts that may already be connected.

**Comment by stevewillard** [comment]
This is now fixed in `0.0.96`+ 

Onboarding status is now derived from `import` status. If the org has an account that is `importing`, `removing`, or `imported`, then you are _not_ onboarding.
